DROP DATABASE CONJUNTOS_RESERVAS;
-- MySQL Script generated by MySQL Workbench
-- Thu Jun  6 21:19:07 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema conjuntos_reservas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema conjuntos_reservas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `conjuntos_reservas` DEFAULT CHARACTER SET utf8 ;
USE `conjuntos_reservas` ;

-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`ROL`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`ROL` (
  `cod_rol` INT NOT NULL AUTO_INCREMENT,
  `rol_name` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`cod_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`HOUSE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`HOUSE` (
  `cod_house` INT NOT NULL AUTO_INCREMENT,
  `house_number` INT NOT NULL,
  `type_habitant` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_house`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`USER`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`USER` (
  `cod_rol` INT NOT NULL,
  `cod_user` INT NOT NULL AUTO_INCREMENT,
  `cod_house` INT NOT NULL,
  `user_name` VARCHAR(45) NOT NULL,
  `user_lastname` VARCHAR(45) NOT NULL,
  `user_birthday` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `user_email` VARCHAR(45) NOT NULL,
  `user_pass` VARCHAR(45) NOT NULL,
  `user_phone` VARCHAR(80) NOT NULL,
  `user_state` TINYINT NOT NULL,
  PRIMARY KEY (`cod_user`),
  INDEX `ind_user_house` (`cod_house` ASC),
  CONSTRAINT `FK_user_rol`
    FOREIGN KEY (`cod_rol`)
    REFERENCES `conjuntos_reservas`.`ROL` (`cod_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_house`
    FOREIGN KEY (`cod_house`)
    REFERENCES `conjuntos_reservas`.`HOUSE` (`cod_house`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`BOOKING`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`BOOKING` (
  `booking_date` DATE NOT NULL,
  `cod_booking` INT NOT NULL AUTO_INCREMENT,
  `cod_user` INT NOT NULL,
  PRIMARY KEY (`cod_booking`, `booking_date`),
  CONSTRAINT `FK_booking`
    FOREIGN KEY (`cod_booking`)
    REFERENCES `conjuntos_reservas`.`HOUSE` (`cod_house`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`CATEGORY_PLACE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`CATEGORY_PLACE` (
  `cod_category` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_category`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`PLACES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`PLACES` (
  `cod_place` INT NOT NULL AUTO_INCREMENT,
  `cod_category` INT NOT NULL,
  `place_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cod_place`),
  INDEX `FK_category_idx` (`cod_category` ASC),
  CONSTRAINT `FK_category`
    FOREIGN KEY (`cod_category`)
    REFERENCES `conjuntos_reservas`.`CATEGORY_PLACE` (`cod_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `conjuntos_reservas`.`LIST_PLACES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `conjuntos_reservas`.`LIST_PLACES` (
  `cod_booking` INT NOT NULL,
  `cod_place` INT NOT NULL,
  `quantity_places` INT NOT NULL,
  INDEX `FK_places_idx` (`cod_booking` ASC),
  INDEX `FK_places_idx1` (`cod_place` ASC),
  CONSTRAINT `FK_list`
    FOREIGN KEY (`cod_booking`)
    REFERENCES `conjuntos_reservas`.`BOOKING` (`cod_booking`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_places`
    FOREIGN KEY (`cod_place`)
    REFERENCES `conjuntos_reservas`.`PLACES` (`cod_place`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
